### ISSUE TITLE
Remove RESULT_CHAR_LIMIT const

### ISSUE THREAD

**Issue by ACheshirov** [norbr9/ulauncher-youtube-search#1]
I'm not sure why you think that song names with more than 70 chars are junk but many songs that I search are having more than 70 chars in its name and it filtered from the results.

**Comment by norbr9** [comment]
This limit prevents junk results from the regex expression. Sometimes it matches strings that are not titles. Although you are right, those strings vary from 300-400 char, so I changed the limit to 300 char... This should do the trick. By the way, youtube recommends titles within 70 char and has a 100 char limit.

Let me know if your search is working now!

**Comment by ACheshirov** [comment]
It's way better right now. Thanks.
Good extension, btw. :)
